# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: CC0-1.0

run:
  name: validation_2023

scenario:
  clusters:
  - 39
  opts:
  - ''
  sector_opts:
  - '2190seg'
  planning_horizons:
  - 2025

snapshots:
  start: "2023-01-01"
  end:   "2024-01-01"

countries: ['AL', 'AT', 'BA', 'BE', 'BG', 'CH', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GR', 'HR', 'HU', 'IE', 'IT', 'LT', 'LU', 'LV', 'ME', 'MK', 'NL', 'NO', 'PL', 'PT', 'RO', 'RS', 'SE', 'SI', 'SK'] #, 'XK']

atlite:
  cutout_directory: cutouts
  default_cutout: europe-2023-sarah3-era5
  nprocesses: 4
  show_progress: true
  cutouts:
    # use 'base' to determine geographical bounds and time span from config
    # base:
      # module: era5
    europe-2023-sarah3-era5:
      module: [sarah, era5] # in priority order
      x: [-12., 42.]
      y: [33., 72.]
      dx: 0.3
      dy: 0.3
      time: ['2023', '2023']

renewable:
  onwind:
    correction_factor: 0.93
  solar:
    correction_factor: 0.854337

lines:
  under_construction: remove
  max_extension: 0
lines:
  s_max_pu: 0.5

links:
  under_construction: remove
  max_extension: 0

transmission_projects:
  enable: false

pypsa_eur:
  Generator:
  - onwind
  - offwind-ac
  - offwind-dc
  - offwind-float
  - solar-hsat
  - solar
  - ror

electricity:
  conventional_generation:
    from_entsoe: false
    year: 2023
  co2limit_enable: false
  co2limit: 1.35e+9 # 2023 value from https://ember-energy.org/data/electricity-data-explorer/?chart=trend&data=emissions

  extendable_carriers:      # forbid new generation & storage
    Generator: []
    StorageUnit: []
    Store: []
  transmission_limit: v1.0  # keep today’s NTCs (default)

  custom_powerplants: (DateIn <= 2023 and DateOut >= 2023)
  powerplants_filter: (Fueltype not in ['Nuclear', 'Hard Coal', 'Lignite', 'Natural Gas'] and DateIn <= 2023 and DateOut >= 2023)

  estimate_renewable_capacities:
    enable: true
    from_gem: false
    year: 2023
    expansion_limit: false
    technology_mapping:
      Offshore: offwind-ac
      Onshore: onwind
      PV: solar

load:
  fill_gaps:
    enable: true
    interpolate_limit: 3
    time_shift_for_large_gaps: 1w
  manual_adjustments: false # false
  scaling_factor: 1.0 
  fixed_year: false # false or year (e.g. 2013)
  supplement_synthetic: true
  distribution_key:
    gdp: 0.6
    population: 0.4

sector:
  transport: true
  heating: true
  biomass: true
  industry: false
  shipping: false
  aviation: false
  agriculture: false
  gas_network: false
  conventional_generation:
    OCGT: gas
    CCGT: gas
    coal: coal
    lignite: lignite
    nuclear: uranium
    oil: oil
  keep_existing_capacities: true

costs:
  year: 2025
  fuel:
    gas: 40.45 # (Avg TTF DA 2023 contracts)
    coal: 16.71 # (from Avg M1 API2 2023 contracts)
    lignite: 7.7 #  (from IEEFA paper)
    oil: 46.8 # (Brent Crude CAL 2023)
  VOM:
    OCGT: 2
    CCGT: 2
    coal: 7
    lignite: 7
  emission_prices:
    enable: true
    co2: 85.59

clustering:
  exclude_carriers: [coal, nuclear, lignite]
#  focus_weights: {'DE': 0.2, 'CZ': 0.06, 'PL': 0.1, 'NL': 0.05, 'IT': 0.15, 'GR': 0.05}

simplify_network:
  remove_stubs_across_borders: true

ember_settings:
  ntc: false
  ntc_cross_country_pf_restriction: false
  ramping: false
  nuclear_decommissioning: true
  ember_gas_price: true
